import fs from "fs/promises"
import path from "path"
import { backupFile, copyDir, copySkillDir, ensureDir, isSafeManagedPath, pathExists, sanitizePathName, writeJson, writeText, writeTextSecure } from "../utils/files"
import type { CodeBuddyBundle } from "../types/codebuddy"
import type { ClaudeMcpServer } from "../types/claude"
import { getLegacyCodeBuddyArtifacts } from "../data/plugin-legacy-artifacts"
import { classifyCodexLegacyPromptOwnership, isLegacyAgentArtifactOwned, isLegacySkillArtifactOwned } from "../utils/legacy-cleanup"

const MANAGED_START_MARKER = "# BEGIN Compound Engineering plugin MCP -- do not edit this block"
const MANAGED_END_MARKER = "# END Compound Engineering plugin MCP"
const PREV_START_MARKER = "# BEGIN compound-plugin Claude Code MCP"
const PREV_END_MARKER = "# END compound-plugin Claude Code MCP"
const LEGACY_MARKER = "# MCP servers synced from Claude Code"
const UNMARKED_LEGACY_MARKER = "# Generated by compound-plugin"
const MANAGED_INSTALL_MANIFEST = "install-manifest.json"

export type CodeBuddyInstallManifest = {
  version: 1
  pluginName: string
  skills: string[]
  prompts: string[]
  agents: string[]
}

export type CodeBuddyWriteOptions = {
  outputIsCodeBuddyRoot?: boolean
}

export async function writeCodeBuddyBundle(
  outputRoot: string,
  bundle: CodeBuddyBundle,
  options: CodeBuddyWriteOptions = {},
): Promise<void> {
  const codebuddyRoot = resolveCodeBuddyRoot(outputRoot, options)
  await ensureDir(codebuddyRoot)

  const pluginName = bundle.pluginName ? sanitizeCodeBuddyPathComponent(bundle.pluginName) : undefined
  const manifest = pluginName ? await readInstallManifest(codebuddyRoot, pluginName) : null
  const currentPrompts = bundle.prompts.map((prompt) => `${sanitizePathName(prompt.name)}.md`)
  const agents = bundle.agents ?? []
  const agentsRoot = pluginName
    ? path.join(codebuddyRoot, "agents", pluginName)
    : path.join(codebuddyRoot, "agents")
  const currentAgents = agents.map((agent) => `${sanitizePathName(agent.name)}.toml`)
  assertNoCodeBuddyAgentFilenameCollisions(agents)

  if (bundle.prompts.length > 0) {
    const promptsDir = path.join(codebuddyRoot, "prompts")
    await cleanupRemovedPrompts(promptsDir, manifest, currentPrompts)
    for (const prompt of bundle.prompts) {
      await writeText(path.join(promptsDir, `${sanitizePathName(prompt.name)}.md`), prompt.content + "\n")
    }
  } else if (pluginName) {
    await cleanupRemovedPrompts(path.join(codebuddyRoot, "prompts"), manifest, [])
  }

  const skillsRoot = pluginName
    ? path.join(codebuddyRoot, "skills", pluginName)
    : path.join(codebuddyRoot, "skills")
  const currentSkills = Array.from(new Set([
    ...bundle.skillDirs.map((skill) => sanitizePathName(skill.name)),
    ...bundle.generatedSkills.map((skill) => sanitizePathName(skill.name)),
    ...(bundle.externallyManagedSkillNames ?? []).map((name) => sanitizePathName(name)),
  ]))
  await cleanupRemovedSkills(skillsRoot, manifest, currentSkills)

  if (bundle.skillDirs.length > 0) {
    for (const skill of bundle.skillDirs) {
      const targetDir = path.join(skillsRoot, sanitizePathName(skill.name))
      await cleanupCurrentManagedSkillDir(targetDir, manifest, sanitizePathName(skill.name))
      await copySkillDir(skill.sourceDir, targetDir)
    }
  }

  if (bundle.generatedSkills.length > 0) {
    for (const skill of bundle.generatedSkills) {
      const skillDir = path.join(skillsRoot, sanitizePathName(skill.name))
      await cleanupCurrentManagedSkillDir(skillDir, manifest, sanitizePathName(skill.name))
      await writeText(path.join(skillDir, "SKILL.md"), skill.content + "\n")
      for (const sidecar of skill.sidecarDirs ?? []) {
        await copyDir(sidecar.sourceDir, path.join(skillDir, sidecar.targetName))
      }
    }
  }

  await cleanupRemovedAgents(agentsRoot, manifest, currentAgents)
  if (agents.length > 0) {
    for (const agent of agents) {
      const agentBaseName = sanitizePathName(agent.name)
      const agentFile = `${agentBaseName}.toml`
      if ((agent.sidecarDirs ?? []).length === 0 && isSafeManagedPath(agentsRoot, agentBaseName)) {
        await fs.rm(path.join(agentsRoot, agentBaseName), { recursive: true, force: true })
      }
      await writeText(path.join(agentsRoot, agentFile), renderCodeBuddyAgentToml(agent) + "\n")
      for (const sidecar of agent.sidecarDirs ?? []) {
        await copyDir(sidecar.sourceDir, path.join(agentsRoot, agentBaseName, sidecar.targetName))
      }
    }
  }

  if (pluginName) {
    await ensureDir(skillsRoot)
    await writeInstallManifest(codebuddyRoot, {
      version: 1,
      pluginName,
      skills: currentSkills,
      prompts: currentPrompts,
      agents: currentAgents,
    })
    await cleanupKnownLegacyCodeBuddyArtifacts(codebuddyRoot, bundle)
    await cleanupLegacyAgentSkillDirs(codebuddyRoot, pluginName, currentSkills, bundle)
    await cleanupPreviousManagedCodeBuddySkillStore(codebuddyRoot, pluginName)
  }

  const configPath = path.join(codebuddyRoot, "settings.json")
  const existingConfig = await readFileSafe(configPath)
  const mcpJson = renderCodeBuddyMcpConfig(bundle.mcpServers)
  const merged = mergeCodeBuddyConfig(existingConfig, mcpJson)
  if (merged !== null) {
    const backupPath = await backupFile(configPath)
    if (backupPath) {
      console.log(`Backed up existing config to ${backupPath}`)
    }
    await writeTextSecure(configPath, merged)
  }

  if (pluginName) {
    const hooksPath = path.join(codebuddyRoot, "hooks.json")
    const existingHooks = await readJsonSafe(hooksPath)
    const pluginHooks = bundle.hooks?.hooks ?? {}
    const mergedHooks = mergeCodeBuddyHooks(existingHooks, pluginHooks, pluginName)
    const mergedContent = JSON.stringify(mergedHooks, null, 2) + "\n"
    const existingContent = existingHooks !== null
      ? JSON.stringify(existingHooks, null, 2) + "\n"
      : null
    const hasHooks = Object.keys((mergedHooks.hooks as Record<string, unknown>) ?? {}).length > 0
    if ((hasHooks || existingHooks !== null) && mergedContent !== existingContent) {
      if (existingHooks !== null) {
        const backupPath = await backupFile(hooksPath)
        if (backupPath) {
          console.log(`Backed up existing hooks to ${backupPath}`)
        }
      }
      await writeTextSecure(hooksPath, mergedContent)
    }
  }
}

function resolveCodeBuddyRoot(outputRoot: string, options: CodeBuddyWriteOptions): string {
  if (options.outputIsCodeBuddyRoot) return outputRoot
  return path.basename(outputRoot) === ".codebuddy" ? outputRoot : path.join(outputRoot, ".codebuddy")
}

function sanitizeCodeBuddyPathComponent(name: string): string {
  return sanitizePathName(name).replace(/[\\/]/g, "-")
}

export async function readCodeBuddyInstallManifest(codebuddyRoot: string, pluginName: string): Promise<CodeBuddyInstallManifest | null> {
  return readInstallManifest(codebuddyRoot, pluginName)
}

async function readInstallManifest(codebuddyRoot: string, pluginName: string): Promise<CodeBuddyInstallManifest | null> {
  const manifestPath = path.join(codebuddyRoot, pluginName, MANAGED_INSTALL_MANIFEST)
  try {
    const raw = await fs.readFile(manifestPath, "utf8")
    const parsed = JSON.parse(raw) as Partial<CodeBuddyInstallManifest>
    if (
      parsed.version === 1 &&
      parsed.pluginName === pluginName &&
      Array.isArray(parsed.skills) &&
      Array.isArray(parsed.prompts)
    ) {
      const agents = Array.isArray(parsed.agents) ? parsed.agents : []
      return {
        version: 1,
        pluginName,
        skills: filterSafeCodeBuddyManifestEntries(parsed.skills, codebuddyRoot, manifestPath, "skills"),
        prompts: filterSafeCodeBuddyManifestEntries(parsed.prompts, codebuddyRoot, manifestPath, "prompts"),
        agents: filterSafeCodeBuddyManifestEntries(agents, codebuddyRoot, manifestPath, "agents"),
      }
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
      console.warn(`Ignoring unreadable CodeBuddy install manifest at ${manifestPath}.`)
    }
  }
  return null
}

function filterSafeCodeBuddyManifestEntries(
  entries: unknown[],
  codebuddyRoot: string,
  manifestPath: string,
  group: string,
): string[] {
  const safe: string[] = []
  for (const entry of entries) {
    if (isSafeManagedPath(codebuddyRoot, entry)) {
      safe.push(entry)
    } else {
      console.warn(
        `Dropping unsafe CodeBuddy install-manifest entry in ${manifestPath} (group "${group}"): ${JSON.stringify(entry)}`,
      )
    }
  }
  return safe
}

async function writeInstallManifest(codebuddyRoot: string, manifest: CodeBuddyInstallManifest): Promise<void> {
  await writeJson(path.join(codebuddyRoot, manifest.pluginName, MANAGED_INSTALL_MANIFEST), manifest)
}

async function cleanupRemovedSkills(
  skillsRoot: string,
  manifest: CodeBuddyInstallManifest | null,
  currentSkills: string[],
): Promise<void> {
  if (!manifest) return
  const current = new Set(currentSkills)
  for (const skillName of manifest.skills) {
    if (current.has(skillName)) continue
    if (!isSafeManagedPath(skillsRoot, skillName)) continue
    await fs.rm(path.join(skillsRoot, skillName), { recursive: true, force: true })
  }
}

async function cleanupRemovedPrompts(
  promptsDir: string,
  manifest: CodeBuddyInstallManifest | null,
  currentPrompts: string[],
): Promise<void> {
  if (!manifest) return
  const current = new Set(currentPrompts)
  for (const promptFile of manifest.prompts) {
    if (current.has(promptFile)) continue
    if (!isSafeManagedPath(promptsDir, promptFile)) continue
    await fs.rm(path.join(promptsDir, promptFile), { force: true })
  }
}

async function cleanupRemovedAgents(
  agentsRoot: string,
  manifest: CodeBuddyInstallManifest | null,
  currentAgents: string[],
): Promise<void> {
  if (!manifest) return
  const current = new Set(currentAgents)
  for (const agentFile of manifest.agents) {
    if (current.has(agentFile)) continue
    if (!isSafeManagedPath(agentsRoot, agentFile)) continue
    await fs.rm(path.join(agentsRoot, agentFile), { force: true })
    await fs.rm(path.join(agentsRoot, path.basename(agentFile, ".toml")), { recursive: true, force: true })
  }
}

async function cleanupCurrentManagedSkillDir(
  targetDir: string,
  manifest: CodeBuddyInstallManifest | null,
  skillName: string,
): Promise<void> {
  if (!manifest?.skills.includes(skillName)) return
  await fs.rm(targetDir, { recursive: true, force: true })
}

async function cleanupKnownLegacyCodeBuddyArtifacts(codebuddyRoot: string, bundle: CodeBuddyBundle): Promise<void> {
  const pluginName = bundle.pluginName
  if (!pluginName) return

  const legacyArtifacts = getLegacyCodeBuddyArtifacts(bundle)
  for (const skillName of legacyArtifacts.skills) {
    const legacySkillPath = path.join(codebuddyRoot, "skills", skillName)
    if (!(await isLegacySkillArtifactOwned(legacySkillPath, skillName))) continue
    await moveLegacyArtifactToBackup(codebuddyRoot, pluginName, "skills", legacySkillPath)
  }

  for (const promptFile of legacyArtifacts.prompts) {
    const legacyPromptPath = path.join(codebuddyRoot, "prompts", promptFile)
    const ownership = await classifyCodexLegacyPromptOwnership(legacyPromptPath)
    if (ownership === "foreign") continue
    await moveLegacyArtifactToBackup(codebuddyRoot, pluginName, "prompts", legacyPromptPath)
  }

  for (const agentFile of legacyArtifacts.agents ?? []) {
    await moveLegacyArtifactToBackup(
      codebuddyRoot,
      pluginName,
      "agents",
      path.join(codebuddyRoot, "agents", pluginName, agentFile),
    )
    const flatAgentPath = path.join(codebuddyRoot, "agents", agentFile)
    if (await isLegacyAgentArtifactOwned(flatAgentPath, path.basename(agentFile, ".toml"), ".toml")) {
      await moveLegacyArtifactToBackup(codebuddyRoot, pluginName, "agents", flatAgentPath)
    }
  }
}

async function cleanupLegacyAgentSkillDirs(
  codebuddyRoot: string,
  pluginName: string,
  currentSkills: string[],
  bundle: CodeBuddyBundle,
): Promise<void> {
  const currentSkillSet = new Set(currentSkills)
  const legacySkillNames = new Set<string>()
  for (const agent of bundle.agents ?? []) {
    legacySkillNames.add(sanitizePathName(agent.name))
  }
  for (const name of getLegacyCodeBuddyArtifacts({
    pluginName,
    prompts: [],
    skillDirs: [],
    generatedSkills: [],
    agents: [],
  }).skills) {
    legacySkillNames.add(name)
  }

  const skillsRoot = path.join(codebuddyRoot, "skills", pluginName)
  for (const skillName of legacySkillNames) {
    if (currentSkillSet.has(skillName)) continue
    await moveLegacyArtifactToBackup(codebuddyRoot, pluginName, "skills", path.join(skillsRoot, skillName))
  }
}

async function cleanupPreviousManagedCodeBuddySkillStore(codebuddyRoot: string, pluginName: string): Promise<void> {
  await fs.rm(path.join(codebuddyRoot, pluginName, "skills"), { recursive: true, force: true })
}

async function moveLegacyArtifactToBackup(
  codebuddyRoot: string,
  pluginName: string,
  kind: "skills" | "prompts" | "agents",
  artifactPath: string,
): Promise<void> {
  if (!(await pathExists(artifactPath))) return
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-")
  const backupDir = path.join(codebuddyRoot, pluginName, "legacy-backup", timestamp, kind)
  const backupPath = path.join(backupDir, path.basename(artifactPath))
  await ensureDir(backupDir)
  await fs.rename(artifactPath, backupPath)
  console.warn(`Moved legacy CodeBuddy ${kind.slice(0, -1)} artifact to ${backupPath}`)
}

export function renderCodeBuddyMcpConfig(mcpServers?: Record<string, ClaudeMcpServer>): string | null {
  if (!mcpServers || Object.keys(mcpServers).length === 0) return null

  const mcpConfig: Record<string, unknown> = {}
  for (const [name, server] of Object.entries(mcpServers)) {
    if (!server.command && !server.url) continue
    const entry: Record<string, unknown> = {}
    if (server.command) {
      entry.command = server.command
      if (server.args && server.args.length > 0) {
        entry.args = server.args
      }
      if (server.env && Object.keys(server.env).length > 0) {
        entry.env = server.env
      }
    } else if (server.url) {
      entry.url = server.url
      if (server.headers && Object.keys(server.headers).length > 0) {
        entry.headers = server.headers
      }
    }
    mcpConfig[name] = entry
  }

  return Object.keys(mcpConfig).length > 0 ? JSON.stringify({ mcpServers: mcpConfig }, null, 2) + "\n" : null
}

async function readFileSafe(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, "utf-8")
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
      throw err
    }
    return ""
  }
}

export function mergeCodeBuddyConfig(existingContent: string, mcpJson: string | null): string | null {
  let existing: Record<string, unknown> = {}
  if (existingContent) {
    try {
      existing = JSON.parse(existingContent)
    } catch {
      return existingContent
    }
  }

  if (!mcpJson) {
    if (!existingContent) return null
    return JSON.stringify(existing, null, 2) + "\n"
  }

  let newMcpConfig: Record<string, unknown>
  try {
    newMcpConfig = JSON.parse(mcpJson)
  } catch {
    return existingContent
  }

  existing.mcpServers = newMcpConfig.mcpServers

  return JSON.stringify(existing, null, 2) + "\n"
}

function assertNoCodeBuddyAgentFilenameCollisions(
  agents: NonNullable<CodeBuddyBundle["agents"]>,
): void {
  const seen = new Map<string, string>()
  for (const agent of agents) {
    const filename = `${sanitizePathName(agent.name)}.toml`
    const prior = seen.get(filename)
    if (prior !== undefined && prior !== agent.name) {
      throw new Error(
        `CodeBuddy agent filename collision: "${prior}" and "${agent.name}" both normalize to ` +
          `"${filename}". Rename one of the source agents so their sanitized filenames differ. ` +
          `A numeric suffix cannot be used here because the TOML filename must match the ` +
          `agent name used for Task(subagent_type: ...) invocations.`,
      )
    }
    seen.set(filename, agent.name)
  }
}

function renderCodeBuddyAgentToml(agent: NonNullable<CodeBuddyBundle["agents"]>[number]): string {
  const lines = [
    `name = ${JSON.stringify(agent.name)}`,
    `description = ${JSON.stringify(agent.description)}`,
    `developer_instructions = ${JSON.stringify(agent.instructions)}`,
  ]
  return lines.join("\n")
}

// ── Hooks ──────────────────────────────────────────────────

async function readJsonSafe(filePath: string): Promise<Record<string, unknown> | null> {
  try {
    const content = await fs.readFile(filePath, "utf8")
    return JSON.parse(content)
  } catch {
    return null
  }
}

type HookEntry = { matcher?: string; hooks: Array<{ type: string; command?: string; prompt?: string; agent?: string; timeout?: number }> }

type ManagedIndex = Record<string, Record<string, number[]>>

export function mergeCodeBuddyHooks(
  existing: Record<string, unknown> | null,
  pluginHooks: Record<string, HookEntry[]>,
  pluginName: string,
): Record<string, unknown> {
  const result: Record<string, unknown[]> = {}
  const managed: ManagedIndex = (existing?._managed as ManagedIndex) ?? {}

  const ownedIndices: Record<string, Set<number>> = {}
  if (managed[pluginName]) {
    for (const [event, indices] of Object.entries(managed[pluginName])) {
      ownedIndices[event] = new Set(indices)
    }
  }

  const existingHooks = (existing?.hooks ?? {}) as Record<string, unknown[]>
  for (const [event, matchers] of Object.entries(existingHooks)) {
    if (!Array.isArray(matchers)) continue
    const owned = ownedIndices[event]
    result[event] = owned
      ? matchers.filter((_, idx) => !owned.has(idx))
      : [...matchers]
  }

  for (const [event, matchers] of Object.entries(result)) {
    result[event] = (matchers as Array<Record<string, unknown>>).filter((m) => {
      if (typeof m === "object" && m !== null && "_source" in m) {
        return m._source !== pluginName
      }
      return true
    })
  }

  const newManagedForPlugin: Record<string, number[]> = {}

  for (const [event, matchers] of Object.entries(pluginHooks)) {
    if (!result[event]) result[event] = []
    const indices: number[] = []
    for (const matcher of matchers) {
      indices.push(result[event].length)
      result[event].push({ ...matcher })
    }
    if (indices.length > 0) {
      newManagedForPlugin[event] = indices
    }
  }

  for (const event of Object.keys(result)) {
    if (result[event].length === 0) delete result[event]
  }

  if (Object.keys(newManagedForPlugin).length > 0) {
    managed[pluginName] = newManagedForPlugin
  } else {
    delete managed[pluginName]
  }

  const output: Record<string, unknown> = { hooks: result }
  if (Object.keys(managed).length > 0) {
    output._managed = managed
  }
  return output
}
